I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/init.rpy", line 67, in script
    init python:
  File "game/init.rpy", line 68, in <module>
    f = open(renpy.loader.transfn("resources/missions.txt"),"r")
Exception: Couldn't find file 'resources/missions.txt'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/init.rpy", line 67, in script
    init python:
  File "C:\Users\user\OneDrive\Рабочий стол\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\user\OneDrive\Рабочий стол\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/init.rpy", line 68, in <module>
    f = open(renpy.loader.transfn("resources/missions.txt"),"r")
  File "C:\Users\user\OneDrive\Рабочий стол\renpy-8.3.2-sdk\renpy\loader.py", line 750, in transfn
    raise Exception("Couldn't find file '%s'." % name)
Exception: Couldn't find file 'resources/missions.txt'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Dead by Deadline 
Sat Dec 21 19:21:39 2024
